[package]
name = "steps01"
version = "0.1.0"
authors = ["nazeudon <nazeudon48112@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.14.0"
num-traits = "0.2.14"